// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerraByte.Infrastructure.Persistence;

#nullable disable

namespace TerraByte.Infrastructure.Migrations
{
    [DbContext(typeof(TerraByteContext))]
    [Migration("20260608053408_AjusteDefensivo")]
    partial class AjusteDefensivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TerraByte.Domain.Entities.Cultura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AguaMM")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<string>("MesesIdeais")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<double>("TempMax")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<double>("TempMin")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<string>("UrlImg")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plantio_terrabyte", (string)null);
                });

            modelBuilder.Entity("TerraByte.Domain.Entities.Defensivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Defensivo_terrabyte", (string)null);
                });

            modelBuilder.Entity("TerraByte.Domain.Entities.RegistroPesquisa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AdequadoPlantio")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<double>("ChuvaPrevistaMm")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<Guid>("CulturaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double>("TempMax")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<double>("TempMin")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<Guid>("TerrenoAgricolaId")
                        .HasColumnType("TEXT");

                    b.Property<double>("UmidadeMed")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CulturaId");

                    b.HasIndex("TerrenoAgricolaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AnalisePlantio_terrabyte", (string)null);
                });

            modelBuilder.Entity("TerraByte.Domain.Entities.TerrenoAgricola", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Areia")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<double>("Argila")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeSolo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<double>("RaioSoloKm")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<double>("Silte")
                        .HasPrecision(8, 2)
                        .HasColumnType("REAL");

                    b.Property<Guid?>("TipoSoloId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoSoloId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EnderecoPlantio_terrabyte", (string)null);
                });

            modelBuilder.Entity("TerraByte.Domain.Entities.TipoSolo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("TipoSolo_terrabyte", (string)null);
                });

            modelBuilder.Entity("TerraByte.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuario_terrabyte", (string)null);
                });

            modelBuilder.Entity("plan_def_terrabyte", b =>
                {
                    b.Property<Guid>("CulturaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DefensivoId")
                        .HasColumnType("TEXT");

                    b.HasKey("CulturaId", "DefensivoId");

                    b.HasIndex("DefensivoId");

                    b.ToTable("plan_def_terrabyte", (string)null);
                });

            modelBuilder.Entity("plan_tp_terrabyte", b =>
                {
                    b.Property<Guid>("CulturaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TipoSoloId")
                        .HasColumnType("TEXT");

                    b.HasKey("CulturaId", "TipoSoloId");

                    b.HasIndex("TipoSoloId");

                    b.ToTable("plan_tp_terrabyte", (string)null);
                });

            modelBuilder.Entity("TerraByte.Domain.Entities.RegistroPesquisa", b =>
                {
                    b.HasOne("TerraByte.Domain.Entities.Cultura", "Cultura")
                        .WithMany("RegistrosPesquisa")
                        .HasForeignKey("CulturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerraByte.Domain.Entities.TerrenoAgricola", "TerrenoAgricola")
                        .WithMany("RegistrosPesquisa")
                        .HasForeignKey("TerrenoAgricolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerraByte.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RegistrosPesquisa")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cultura");

                    b.Navigation("TerrenoAgricola");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TerraByte.Domain.Entities.TerrenoAgricola", b =>
                {
                    b.HasOne("TerraByte.Domain.Entities.TipoSolo", "TipoSolo")
                        .WithMany("TerrenosAgricolas")
                        .HasForeignKey("TipoSoloId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TerraByte.Domain.Entities.Usuario", "Usuario")
                        .WithMany("TerrenosAgricolas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoSolo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("plan_def_terrabyte", b =>
                {
                    b.HasOne("TerraByte.Domain.Entities.Cultura", null)
                        .WithMany()
                        .HasForeignKey("CulturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerraByte.Domain.Entities.Defensivo", null)
                        .WithMany()
                        .HasForeignKey("DefensivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("plan_tp_terrabyte", b =>
                {
                    b.HasOne("TerraByte.Domain.Entities.Cultura", null)
                        .WithMany()
                        .HasForeignKey("CulturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TerraByte.Domain.Entities.TipoSolo", null)
                        .WithMany()
                        .HasForeignKey("TipoSoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TerraByte.Domain.Entities.Cultura", b =>
                {
                    b.Navigation("RegistrosPesquisa");
                });

            modelBuilder.Entity("TerraByte.Domain.Entities.TerrenoAgricola", b =>
                {
                    b.Navigation("RegistrosPesquisa");
                });

            modelBuilder.Entity("TerraByte.Domain.Entities.TipoSolo", b =>
                {
                    b.Navigation("TerrenosAgricolas");
                });

            modelBuilder.Entity("TerraByte.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RegistrosPesquisa");

                    b.Navigation("TerrenosAgricolas");
                });
#pragma warning restore 612, 618
        }
    }
}
