// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TerraByte.Infraestrutura.Persistencia;

#nullable disable

namespace TerraByte.Infraestrutura.Migrations
{
    [DbContext(typeof(TerraByteContext))]
    partial class InstantaneoModeloTerraByteContext : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder montadorModelo)
        {
#pragma warning disable 612, 618
            montadorModelo.HasAnnotation("ProductVersion", "9.0.5");

            montadorModelo.Entity("TerraByte.Dominio.Entidades.Cultura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TerrenoAgricolaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataPlantio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeSemente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TerrenoAgricolaId");

                    b.ToTable("TB_Crops", (string)null);
                });

            montadorModelo.Entity("TerraByte.Dominio.Entidades.TerrenoAgricola", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<double>("Argila")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<double>("Areia")
                        .HasColumnType("REAL");

                    b.Property<double>("Silte")
                        .HasColumnType("REAL");

                    b.Property<string>("NomeSolo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<double>("RaioSoloKm")
                        .HasColumnType("REAL");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_FarmPlots", (string)null);
                });

            montadorModelo.Entity("TerraByte.Dominio.Entidades.RegistroPesquisa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TerrenoAgricolaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SolicitadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TerrenoAgricolaId");

                    b.ToTable("TB_ResearchSnapshots", (string)null);
                });

            montadorModelo.Entity("TerraByte.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TB_Users", (string)null);
                });

            montadorModelo.Entity("TerraByte.Dominio.Entidades.Cultura", b =>
                {
                    b.HasOne("TerraByte.Dominio.Entidades.TerrenoAgricola", "TerrenoAgricola")
                        .WithMany("Culturas")
                        .HasForeignKey("TerrenoAgricolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerrenoAgricola");
                });

            montadorModelo.Entity("TerraByte.Dominio.Entidades.TerrenoAgricola", b =>
                {
                    b.HasOne("TerraByte.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("TerrenosAgricolas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            montadorModelo.Entity("TerraByte.Dominio.Entidades.RegistroPesquisa", b =>
                {
                    b.HasOne("TerraByte.Dominio.Entidades.TerrenoAgricola", "TerrenoAgricola")
                        .WithMany("RegistrosPesquisa")
                        .HasForeignKey("TerrenoAgricolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TerrenoAgricola");
                });

            montadorModelo.Entity("TerraByte.Dominio.Entidades.TerrenoAgricola", b =>
                {
                    b.Navigation("Culturas");

                    b.Navigation("RegistrosPesquisa");
                });

            montadorModelo.Entity("TerraByte.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("TerrenosAgricolas");
                });
#pragma warning restore 612, 618
        }
    }
}


